name: Deploy app

on:
  push:
    branch: ["dev"]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  build:
    name: Deploy to fly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create .env file
        run: touch .env
          echo PORT=${{ secrets.PORT }}
          echo MONGO_URI=${{ secrets.MONGO_URI }}
          cat .env
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy
