name: Deploy app

on:
  push:
    branch: ["dev"]

jobs:
  build:
    name: Deploy to fly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create .env file
        run: touch .env
          echo PORT=${{ secrets.PORT }} >> .env
          echo MONGO_URI=${{ secrets.MONGO_URI }} >> .env
          cat .env
      - name: Setup Fly
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy
        run: echo ${{ secrets.FLY_API_TOKEN }}
          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
